# Generated by Django 4.0.2 on 2025-10-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_ticket_unique_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
